[package]
name = "andamento-controller"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[lib]
name = "andamento_controller"
path = "src/main.rs"

[[bin]]
name = "andamento-controller"
path = "src/main.rs"

[dependencies]
log = "0.4"
serde.workspace = true
serde_json.workspace = true
andamento-shared.workspace = true
zellij-tile.workspace = true
